hotlink: false
origin: 'https://coronavirus3dprint.com'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
